name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Descargar artefacto HTML
        uses: actions/download-artifact@v2
        with:
          name: HTML
          path: .

      # Aquí puedes agregar pasos adicionales para implementar el artefacto en tu entorno de producción
