name: CI
on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3
      
      - name: Publicar artefacto HTML
        uses: actions/upload-artifact@v3
        with:
          name: HTML
          path: .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3
      - name: Descargar artefacto HTML
        uses: actions/download-artifact@v3
        with:
          name: HTML